# Generated by Django 3.2.7 on 2021-10-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='Genero',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
