# Generated by Django 3.2.7 on 2021-10-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211003_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='Nombres',
        ),
        migrations.AddField(
            model_name='type',
            name='Nombre',
            field=models.CharField(default=2, max_length=150, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
